include:
  - project: "Infrastructure/openshift-images/ci-templates"
    file: "/buildah.yml"

stages:
  - test
  - deploy

build-image:
  stage: test
  extends:
    - .buildah
  variables:
    CI_COMMIT_REF_PROTECTED: "false"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'push'

tests:
  stage: test
  needs: []
  image: oven/bun:1
  script:
    - bun install --frozen-lockfile
    - bun run typecheck
    - bun run lint
    - bun test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'push'

deploy-prod:
  stage: deploy
  extends:
    - .buildah
  tags:
    - aarch64
  variables:
    OCI_IMAGE_NAME: "odrs"
    OCI_IMAGE_TAG: "aarch64-latest"
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
      when: on_success
